polls/urls.py
from django.conf.urls import patterns, include, url
from polls import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'testsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='index'),
    # url(r'^(?P<question_id>\d+)$', views.detail, name='detail'),
    # url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^vote/$', views.vote, name='vote'),
    url(r'^search/$', views.search, name='search'),
    url(r'^cookies/$', views.cookies_, name='cookies'),
)

pythontestsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', include('polls.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^userprofile/', include('userprofile.urls', namespace="userprofile")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^social/', include('social_auth.urls')),
    url(r'^accounts/profile/$', include('polls.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.conf.urls import patterns, include, url
from userprofile import views


urlpatterns = patterns('',
    url(r'^user/$', views.user_, name='user'),
    url(r'^register/$', views.register_, name='register'),
    url(r'^(?P<user_name>\w+)/public/$', views.public_, name='public'),
    url(r'^login/$', views.login_, name='login'),
    url(r'^logout/$', views.logout_, name='logout'),
)

polls/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_delete
from signals import *


class Cookie(models.Model):

    rating = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    description = models.TextField()
    img = models.ImageField(upload_to="cookies")
    user = models.ManyToManyField(User)

pre_save.connect(del_img, sender=Cookie)
post_delete.connect(del_img_with_post, sender=Cookie)


class Comments(models.Model):
    cookie_id = models.ForeignKey(Cookie)
    user_id = models.ForeignKey(User)
    comment = models.TextField()

polls/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Cookie, Comments
from django.utils.translation import gettext as _


class VoteForm(forms.ModelForm):

    class Meta:
        model = Cookie
        CHOICES = (('1', '1',), ('2', '2',), ('3', '3',), ('4', '4',), ('5', '5',))
        fields = ("rating", )
        widgets = {"rating": forms.RadioSelect(choices=CHOICES)}


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ("comment",)
        widgets = {"comment": forms.Textarea(attrs={"placeholder": _("Отзыв"),"id": "poll_comment", "class": "form-control"}), }

polls/views.py
# -*- coding: utf-8 -*-
from urllib import urlopen
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.shortcuts import render, get_object_or_404, redirect
from polls.forms import VoteForm, CommentForm
from polls.models import Cookie, Comments
from django.contrib.auth import get_user
# from social_auth.signals import pre_update
# from django.dispatch import receiver
from django.utils import translation
import functions


# @receiver(pre_update)
# def update_person_details(sender, **kwargs):
#     raise("qweqweqew")
#     person = kwargs.get('user')
#     details = kwargs.get('details')
#     load_person_avatar(sender, person, kwargs.get('response'))
#
#
# def load_person_avatar(sender, person, info):
#     image_url = None
#
#     if sender.name == 'twitter':
#         image_url = info.get('profile_image_url')
#         if not 'default_profile' in image_url:
#             image_url = image_url.replace('_normal', '_bigger')
#         else: # No real image
#             image_url = None
#     if image_url:
#         # try:
#             image_content = urlopen(image_url)
#
#             # Facebook default image check
#             if sender.name == 'facebook' and 'image/gif' in str(image_content.info()):
#                 return
#
#             image_name = default_storage.get_available_name(person.avatar.field.upload_to + '/' + str(person.id) + '.' + image_content.headers.subtype)
#             raise()
#             person.avatar.save(image_name, ContentFile(image_content.read()))
#             person.save()
#         # except Exception:
#         #     pass # Here we completely do not care about errors
        

def index(request):
    cookies = Cookie.objects.all().order_by('-rating')[:3]
    result = functions.get_all_forms(request, cookies)

    # li = get_language_info(get_language())
    # print(li['name'], li['name_local'], li['bidi'])
    # raise()
    # translation.activate("en")

    return render(request, "polls/index.html", result)


def cookies_(request):
    cookies = Cookie.objects.all()
    result = functions.get_all_forms(request, cookies)
    return render(request, "polls/cookies.html", result)


def search(request):
    if 'search' in request.POST:
        cookies = Cookie.objects.filter(name__contains=request.POST['search'])
        result = functions.get_all_forms(request, cookies)
        return render(request, "polls/cookies.html", result)
    else:
        return redirect(request.META['HTTP_REFERER'])


def vote(request):

    user = get_user(request)
    if not user.is_anonymous():
        if 'vote_btn' in request.POST:
            cookie_obj = get_object_or_404(Cookie, pk=request.POST['cookie_id'])

            if "rating" in request.POST:
                vote_form = VoteForm(request.POST, instance=cookie_obj)
                old_rating = cookie_obj.rating
                if vote_form.is_valid():
                    all_values = []
                    # // проверяем, полученное значение POST["rating"]
                    for radio_values in vote_form.Meta.CHOICES:
                        all_values.append(radio_values[0])
                    # // что бы ещё не голосовал
                    if user not in cookie_obj.user.all():

                        # // если такое есть, то записываем
                        if request.POST["rating"] in all_values:
                            cookie_obj.rating = old_rating + int(request.POST["rating"])
                            cookie_obj.user.add(user)
                            cookie_obj.save()
                            vote_form.save()

            if "comment" in request.POST:
                if len(request.POST["comment"]) > 0:
                    comment_obj = Comments(cookie_id=cookie_obj, user_id=user)
                    comment_form = CommentForm(request.POST, instance=comment_obj)
                    if comment_form.is_valid():
                        cookie_obj.user.add(user)
                        cookie_obj.save()
                        comment_form.save()

    if 'HTTP_REFERER' in request.META:
        path_to_redirect = request.META['HTTP_REFERER']
    else:
        path_to_redirect = "polls/index.html"

    return redirect(path_to_redirect)

polls/templates/polls/base.html
{% include 'polls/header.html' %}
{% load staticfiles %}
{% load i18n %}


<h2>{% block page_name %}{% trans "Самые популярные печеньки" %}{% endblock %}</h2>

<div class="row">
    <div class="col-md-9">
    {% block posts %}
        {% if cookies %}
            {% for cookie in cookies %}

                <div class="media">
                    <a class="pull-left" href="#">
                        <img height="64" width="64" class="media-object" src="/media/{{ cookie.img }}" alt="cookie">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{ cookie.name }}</h4>
                        {{ cookie.description }}
                    </div>
                    <br/>
                    <div class="col-md-12" >
                    {% block vote %}
                        {% if not user.is_anonymous and user not in cookie.user.all %}
                            <form action="{% url 'polls:vote' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="cookie_id" value="{{ cookie.id  }}" />

                                <div class="col-md-12" >
                                    <div class="col-md-2" >
                                        {% trans "Оцените печеньку" %}
                                    </div>

                                    {% for i in voteForm.rating %}
                                        <div class="col-md-1" >
                                             {{ i }}
                                        </div>
                                    {% endfor %}

                                    <div class="col-md-5" >
                                        {{ commentForm.comment }}
                                    </div>
                                </div>

                                <div class="col-md-12" >
                                        <input class="btn btn-primary btn-small fullwidth" name="vote_btn"  type="submit" value="{% trans  "Проголосовать и оставить отзыв" %}" />
                                </div>
                            </form>
                        {%endif%}
                    {% endblock vote %}
                    </div>
                    <div class="col-md-12" >
                    {% block comments %}
                        <br/>
                        <b>{% trans "Рейтинг печеньки" %} - {{ cookie.rating }}</b>
                        <br/>
                        <br/>
                        <b>{% trans "Комментарии" %}:</b>
                        {% for field in result %}
                            {% if field.0 == cookie.pk %}
                                <p><a href="{% url 'userprofile:public' field.1 %}" >{{ field.1 }}</a> {% trans  "написал" %}: {{ field.2 }}</p>
                            {% endif %}
                        {% endfor %}
                    {% endblock comments %}
                    </div>
                </div>
                 <br/> <br/>

            {% endfor %}
        {% else %}
            <p>{% trans "Таких печенек нет" %} :(</p>
        {% endif %}
    {% endblock posts %}
    </div>

    <div id="sidebar" class="col-md-3" >

    {% block user %}
        <p class="error" >{{ msg }}</p>
        {% if not user.is_anonymous %}

                <h4>{% trans "Добро пожаловать" %} <a href="{% url 'userprofile:user' %}" class="navbar-link" >{{ user }}</a></h4>
                <a href="{% url 'userprofile:logout' %}" class="navbar-link" >{% trans "Выйти" %}</a>
                <br />
        {% else %}
            <h4>{% trans "Войти" %}</h4>
            <form method="post" action="{% url 'userprofile:login' %}">
                {% csrf_token %}
                {% for elem in form %}
                {{ elem }}<br />
                {% endfor %}
                <input type="submit" value="{% trans "Войти" %}" class="btn btn-primary form-control" /><br><br>
                <a href="{% url 'userprofile:register' %}" class="navbar-link" >{% trans "Зарегестрироваться" %}</a><br><br>
            </form>

            <a href="{% url 'socialauth_begin' 'twitter' %}" target="_blank">twitter</a>

        {% endif%}
    {% endblock user %}

    </div>
</div>

{% include 'polls/footer.html' %}

polls/templates/polls/cookies.html
{% extends 'polls/base.html' %}
{% load i18n %}
        {% block page_name %}{% trans "Все печеньки" %}{% endblock %}

polls/templates/polls/footer.html
        </div>
    <body>
<html>

polls/templates/polls/header.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="{% static "polls/style.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet" media="screen">
    <script src="{% static "jquery.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</head>
<body>
    <div id="main" class="container">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
              <div class="navbar-header">
                  <div class="navbar-brand" >{% trans "Любителям печенек" %}</div>
              </div>
              <ul class="nav navbar-nav">
                <li><a href="{% url 'polls:index' %}">{% trans "Главная" %}</a></li>
                <li><a href="{% url 'polls:cookies' %}">{% trans "Печеньки" %}</a></li>
              </ul>
              <form method="post" action="{% url 'polls:search' %}" class="navbar-form navbar-right" role="search">
                  {% csrf_token %}
                  <div class="form-group">
                    <input name="search" type="text" class="form-control" placeholder="{% trans "Название печеньки" %}" />
                  </div>
                  <button type="submit" class="btn btn-default" value="find">{% trans "Найти" %}</button>
              </form>

              <form method="post" action="" class="navbar-form navbar-right" role="search">
                  {% csrf_token %}
                  <div class="btn-group">
                      <select class="btn" name="language">
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <option  value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                        {% endfor %}
                      </select>
                  </div>
                  <button type="submit" class="btn" value="find">{% trans "Перевести" %}</button>
              </form>

          </div>
        </nav>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}